### ISSUE TITLE
Adde description to the repository

### ISSUE THREAD

**Issue by klugier** [anboto/Xlnt#1]
The repository name is empty "About:xNo description, website, or topics provided.". I am using description in UppHub, so it should be present before adding repo into registry.

**Comment by izabala123** [comment]
May it be "Library for reading/writing spreadsheets from/to XLSX files"?

**Comment by klugier** [comment]
I think it should be fine.

**Comment by izabala123** [comment]
Hi Zbigniew, is it all OK?

**Comment by klugier** [comment]
@izabala123, yes it's OK, but you didn't change it in the repository.

**Comment by izabala123** [comment]
Oh, thank you. Now I understand. I think it is done.

**Comment by klugier** [comment]
Now, it's fine. I created PR for UppHub https://github.com/ultimatepp/UppHub/pull/31 and it is waiting for Oblivion approval.
